class DietDishes {
  static final Map<String, List<String>> dietDishes = {
    'Anything': [
      'Egg',
      'Foul',
      'Rice',
      'Pasta',
      'Chicken',
      'Beef',
      'Fish',
      'Vegetables',
      'Fruits',
      'Bread',
      'Cheese',
      'Yogurt',
      'Potatoes',
      'Nuts',
      'Salads',
      'Smoothies',
      'Sausages',
      'Grains',
      'Deli Meats',
      'Pies',
      'Tacos',
      'Pizza',
      'Burgers',
      'Wraps',
      'Nachos',
      'Cookies',
      'Brownies',
      'Ice Cream',
      'Pudding',
      'Pancakes',
      // Added breakfast items
      'Omelettes',
      'French Toast',
      'Breakfast Burritos',
      'Smoothie Bowls',
      'Bagels',
      'Breakfast Sandwiches',
      'Chia Pudding',
      'Breakfast Muffins',
    ],
    'keto': [
      'Avocado',
      'Egg',
      'Bacon',
      'Cheese',
      'Heavy Cream',
      'Olive Oil',
      'Salmon',
      'Nuts',
      'Broccoli',
      'Zucchini Noodles',
      'Cauliflower Rice',
      'Pork Rinds',
      'Coconut Oil',
      'Kale',
      'Spinach',
      'Mushrooms',
      'Pumpkin Seeds',
      'Pepperoni',
      'Sausage',
      'Berries (in moderation)',
      'Cream Cheese',
      'Beef Jerky',
      'Shirataki Noodles',
      'Radishes',
      'Cabbage',
      'Asparagus',
      'Brussels Sprouts',
      'Eggplant',
      // Added breakfast items
      'Keto Pancakes',
      'Egg Muffins',
      'Coconut Yogurt',
      'Keto Smoothies',
      'Baked Avocado Eggs',
    ],
    'Vegetarian': [
      'Tofu',
      'Lentils',
      'Broccoli',
      'Chickpeas',
      'Quinoa',
      'Spinach',
      'Bell Peppers',
      'Eggplant',
      'Mushrooms',
      'Avocado',
      'Black Beans',
      'Carrots',
      'Cabbage',
      'Peas',
      'Rice',
      'Pasta',
      'Vegetarian Sausages',
      'Nuts',
      'Seeds',
      'Vegetable Broth',
      'Sweet Potatoes',
      'Vegetarian Chili',
      'Stuffed Peppers',
      'Vegetable Stir-Fry',
      'Falafel',
      'Vegetable Soup',
      'Pesto Pasta',
      'Veggie Pizza',
      // Added breakfast items
      'Vegetarian Omelettes',
      'Fruit Smoothies',
      'Breakfast Quinoa Bowl',
      'Chia Seed Pudding',
      'Avocado Toast',
    ],
    'Vegan': [
      'Beans',
      'Quinoa',
      'Hummus',
      'Tofu',
      'Tempeh',
      'Nuts',
      'Chia Seeds',
      'Fruits',
      'Vegetables',
      'Oats',
      'Soy Milk',
      'Almond Milk',
      'Coconut Yogurt',
      'Nut Butter',
      'Leafy Greens',
      'Brown Rice',
      'Vegetable Stir-Fry',
      'Veggie Burgers',
      'Seeds',
      'Plant-Based Cheese',
      'Peanut Butter',
      'Coconut Milk',
      'Vegan Pancakes',
      'Vegan Pizza',
      'Vegan Pasta',
      'Nut Milk',
      'Fruit Smoothies',
      'Chickpea Salad',
      'Vegan Curry',
      // Added breakfast items
      'Vegan French Toast',
      'Vegan Smoothies',
      'Oatmeal',
      'Vegan Breakfast Burritos',
      'Acai Bowls',
    ],
    // 'Paleo': [
    //   'Chicken',
    //   'Fish',
    //   'Sweet Potatoes',
    //   'Eggs',
    //   'Nuts',
    //   'Fruits',
    //   'Leafy Greens',
    //   'Berries',
    //   'Grass-Fed Beef',
    //   'Coconut Oil',
    //   'Wild-Caught Fish',
    //   'Avocado',
    //   'Pork',
    //   'Butternut Squash',
    //   'Pumpkin',
    //   'Zucchini',
    //   'Almonds',
    //   'Cashews',
    //   'Maple Syrup (in moderation)',
    //   'Sweet Potatoes',
    //   'Olive Oil',
    //   'Beef Jerky (natural)',
    //   'Coconut Flour',
    //   'Vegetables',
    //   'Paleo Bread',
    //   'Paleo Snacks',
    //   'Bacon',
    //   // Added breakfast items
    //   'Paleo Smoothies',
    //   'Eggs and Bacon',
    //   'Paleo Pancakes',
    //   'Sweet Potato Hash',
    //   'Fruit Salad',
    // ],
    // 'Mediterranean': [
    //   'Olive Oil',
    //   'Tomatoes',
    //   'Fish',
    //   'Chickpeas',
    //   'Feta Cheese',
    //   'Eggplant',
    //   'Spinach',
    //   'Olives',
    //   'Cucumbers',
    //   'Quinoa',
    //   'Pita Bread',
    //   'Hummus',
    //   'Bell Peppers',
    //   'Zucchini',
    //   'Garlic',
    //   'Lentils',
    //   'Artichokes',
    //   'Basil',
    //   'Oregano',
    //   'Pomegranate',
    //   'Tahini',
    //   'Greek Yogurt',
    //   'Egg Salad',
    //   'Mediterranean Grain Bowl',
    //   'Stuffed Grape Leaves',
    //   'Seafood Paella',
    //   'Roasted Red Peppers',
    //   // Added breakfast items
    //   'Mediterranean Omelette',
    //   'Greek Yogurt Parfait',
    //   'Shakshuka',
    //   'Feta and Spinach Wraps',
    //   'Hummus Toast',
    // ],
    // 'Pescatarian': [
    //   'Salmon',
    //   'Shrimp',
    //   'Tuna',
    //   'Mackerel',
    //   'Sardines',
    //   'Fish Tacos',
    //   'Seafood Pasta',
    //   'Vegetables',
    //   'Rice',
    //   'Quinoa',
    //   'Crab',
    //   'Clams',
    //   'Octopus',
    //   'Seaweed',
    //   'Fish Curry',
    //   'Seafood Salad',
    //   'Lobster',
    //   'Mussels',
    //   'Oysters',
    //   'Seafood Stir-Fry',
    //   'Fish Sandwiches',
    //   'Prawn Salad',
    //   'Tuna Salad',
    //   'Ceviche',
    //   'Fish Soup',
    //   'Sushi',
    //   'Seafood Risotto',
    //   // Added breakfast items
    //   'Smoked Salmon on Bagels',
    //   'Seafood Omelette',
    //   'Chia Seed Pudding',
    //   'Breakfast Sushi Rolls',
    //   'Avocado Toast with Salmon',
    // ],
    // 'Gluten-Free': [
    //   'Rice',
    //   'Quinoa',
    //   'Potatoes',
    //   'Corn',
    //   'Nuts',
    //   'Fruits',
    //   'Vegetables',
    //   'Gluten-Free Bread',
    //   'Oats (certified gluten-free)',
    //   'Rice Pasta',
    //   'Chickpea Flour',
    //   'Almond Flour',
    //   'Potato Starch',
    //   'Tapioca Starch',
    //   'Millet',
    //   'Sorghum',
    //   'Buckwheat',
    //   'Coconut Flour',
    //   'Gluten-Free Cereals',
    //   'Polenta',
    //   'Gluten-Free Pizza',
    //   'Gluten-Free Pancakes',
    //   'Gluten-Free Cookies',
    //   'Rice Cakes',
    //   'Gluten-Free Granola',
    //   'Gluten-Free Muffins',
    //   'Vegetable Chips',
    //   'Popcorn',
    //   // Added breakfast items
    //   'Gluten-Free Oatmeal',
    //   'Breakfast Smoothies',
    //   'Chia Pudding',
    //   'Gluten-Free Breakfast Burritos',
    //   'Fruit Salad',
    // ],
  };

  static List<String> getDishesForDiet(String? diet) {
    return dietDishes[diet] ?? [];
  }
}
