class DietDishes {
  static final Map<String, List<String>> dietDishes = {
    'Anything': [
      'Egg',
      'Foul',
      'Rice',
      'Pasta',
      'Chicken',
      'Beef',
      'Fish',
      'Vegetables',
      'Fruits',
      'Bread',
      'Cheese',
      'Yogurt',
      'Potatoes',
      'Nuts',
      'Salads',
      'Smoothies',
      'Sausages',
      'Grains',
      'Deli Meats',
      'Pies',
    ],
    'Keto': [
      'Avocado',
      'Egg',
      'Bacon',
      'Cheese',
      'Heavy Cream',
      'Olive Oil',
      'Salmon',
      'Nuts',
      'Broccoli',
      'Zucchini Noodles',
      'Cauliflower Rice',
      'Pork Rinds',
      'Coconut Oil',
      'Kale',
      'Spinach',
      'Mushrooms',
      'Pumpkin Seeds',
      'Pepperoni',
      'Sausage',
      'Berries (in moderation)',
    ],
    'Vegetarian': [
      'Tofu',
      'Lentils',
      'Broccoli',
      'Chickpeas',
      'Quinoa',
      'Spinach',
      'Bell Peppers',
      'Eggplant',
      'Mushrooms',
      'Avocado',
      'Black Beans',
      'Carrots',
      'Cabbage',
      'Peas',
      'Rice',
      'Pasta',
      'Vegetarian Sausages',
      'Nuts',
      'Seeds',
      'Vegetable Broth',
    ],
    'Vegan': [
      'Beans',
      'Quinoa',
      'Hummus',
      'Tofu',
      'Tempeh',
      'Nuts',
      'Chia Seeds',
      'Fruits',
      'Vegetables',
      'Oats',
      'Soy Milk',
      'Almond Milk',
      'Coconut Yogurt',
      'Nut Butter',
      'Leafy Greens',
      'Brown Rice',
      'Vegetable Stir-Fry',
      'Veggie Burgers',
      'Seeds',
      'Plant-Based Cheese',
    ],
    'Paleo': [
      'Chicken',
      'Fish',
      'Sweet Potatoes',
      'Eggs',
      'Nuts',
      'Fruits',
      'Leafy Greens',
      'Berries',
      'Grass-Fed Beef',
      'Coconut Oil',
      'Wild-Caught Fish',
      'Avocado',
      'Pork',
      'Butternut Squash',
      'Pumpkin',
      'Zucchini',
      'Almonds',
      'Cashews',
      'Maple Syrup (in moderation)',
    ],
    'Mediterranean': [
      'Olive Oil',
      'Tomatoes',
      'Fish',
      'Chickpeas',
      'Feta Cheese',
      'Eggplant',
      'Spinach',
      'Olives',
      'Cucumbers',
      'Quinoa',
      'Pita Bread',
      'Hummus',
      'Bell Peppers',
      'Zucchini',
      'Garlic',
      'Lentils',
      'Artichokes',
      'Basil',
      'Oregano',
    ],
    'Pescatarian': [
      'Salmon',
      'Shrimp',
      'Tuna',
      'Mackerel',
      'Sardines',
      'Fish Tacos',
      'Seafood Pasta',
      'Vegetables',
      'Rice',
      'Quinoa',
      'Crab',
      'Clams',
      'Octopus',
      'Seaweed',
      'Fish Curry',
      'Seafood Salad',
      'Lobster',
      'Mussels',
      'Oysters',
      'Seafood Stir-Fry',
    ],
    'Gluten-Free': [
      'Rice',
      'Quinoa',
      'Potatoes',
      'Corn',
      'Nuts',
      'Fruits',
      'Vegetables',
      'Gluten-Free Bread',
      'Oats (certified gluten-free)',
      'Rice Pasta',
      'Chickpea Flour',
      'Almond Flour',
      'Potato Starch',
      'Tapioca Starch',
      'Millet',
      'Sorghum',
      'Buckwheat',
      'Coconut Flour',
      'Gluten-Free Cereals',
    ],
  };
  static List<String> getDishesForDiet(String? diet) {
    return dietDishes[diet] ?? [];
  }
}
