// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK5pbA_d0tAsu5yp0Zq34SN3UZsX7Idvo',
    appId: '1:528529121967:web:8ddc35f951611724bfea5a',
    messagingSenderId: '528529121967',
    projectId: 'project-without-name-159ef',
    authDomain: 'project-without-name-159ef.firebaseapp.com',
    storageBucket: 'project-without-name-159ef.appspot.com',
    measurementId: 'G-ZWBWTXS6YK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-pi0SyQkaBJ0rG7YppqgR4WxuBJ9siCw',
    appId: '1:528529121967:ios:e8b84d7a02522539bfea5a',
    messagingSenderId: '528529121967',
    projectId: 'project-without-name-159ef',
    storageBucket: 'project-without-name-159ef.appspot.com',
    iosBundleId: 'com.example.loseWeightEatHealthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-pi0SyQkaBJ0rG7YppqgR4WxuBJ9siCw',
    appId: '1:528529121967:ios:e8b84d7a02522539bfea5a',
    messagingSenderId: '528529121967',
    projectId: 'project-without-name-159ef',
    storageBucket: 'project-without-name-159ef.appspot.com',
    iosBundleId: 'com.example.loseWeightEatHealthy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK5pbA_d0tAsu5yp0Zq34SN3UZsX7Idvo',
    appId: '1:528529121967:web:410061454ba59ab2bfea5a',
    messagingSenderId: '528529121967',
    projectId: 'project-without-name-159ef',
    authDomain: 'project-without-name-159ef.firebaseapp.com',
    storageBucket: 'project-without-name-159ef.appspot.com',
    measurementId: 'G-XXTW53E1X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLRnrW-vO5U311DjgVM6JEbS33xIwhpIA',
    appId: '1:528529121967:android:1ba110bf571de710bfea5a',
    messagingSenderId: '528529121967',
    projectId: 'project-without-name-159ef',
    storageBucket: 'project-without-name-159ef.appspot.com',
  );

}